config/routes.rb
Rails.application.routes.draw do
   devise_for :users

  
  match 'results', to: 'exercises#results', via: 'post', as: 'results'
  get 'foods/new'
  get 'exercises/new'
 

  root                 'exercises#show'#on initial view, show the form to calculate
  get 'about'       => 'static_pages#about' 
  get 'settings'    => 'static_pages#settings'
  get 'food'        => 'foods#show'
  get 'exercise'    => 'exercises#show'
  get 'exercise_database' => 'exercises#database'
  get 'credits' => 'static_pages#credits'
  get 'exercise_categories' => 'exercises#categories'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
end

app/models/food.rb
class Food < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # instead of deleting, indicate the user requested a delete & timestamp it  
  def soft_delete  
    update_attribute(:deleted_at, Time.current)  
  end  

  # ensure user account is active  
  def active_for_authentication?  
    super && !deleted_at  
  end  

  # provide a custom message for a deleted account   
  def inactive_message   
    !deleted_at ? super : :deleted_account  
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
   
   def database
      #Pagination for will_paginate
      @exercises = Exercise.paginate(page: params[:page], :per_page => '10')
      @exerciseCount = Exercise.count
      @categoryCount = Exercise.distinct.count(:category)
   end
   
   def categories
      #Count the unique categories 
      @descriptionCount = Exercise.group(:category).uniq.count

   end
   
    
   def show
      #This corresponds to show.html.erb and allows the form to select from the model (database) items to be shown
   
      #select the exercises
      @exerciseOptions = Exercise.pluck(:description, :id) 
     
   
      #select the food and limit it to 5 itmes
      @foodOptions = Food.limit(5).pluck(:name, :id)
         
      
   end
    
   def results
      #Find by id from the results form 
      
      #convert the weight from the results form to kilograms
       
      @weightResult = 0
      if @weightResult <= 0
         @weightResult = 175 / 2.2046
      else
         @weightResult = params[:results][:weight].to_i / 2.2046
      end
      
      #select the exercise from the results drop down and convert it to an integer
      @exerciseResult = Exercise.find_by_id(params[:results][:exercise].to_i) 
      @foodResult = Food.find_by_id(params[:results][:food].to_i) 
      
      #calculate the math formula below
      
      #Formula: MET Value x 3.5 x body weight (kg) / 200 = calories burned per minute
      @calc = ((@exerciseResult.met * 3.5 * @weightResult) / 200).to_f
      #calculate the minutes it would take to burn off the food item and round it up to nearest whole number
         @minutes = (@foodResult.calories / @calc).round
       
   end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  require 'httparty'
  def new
  end
  
  def show
    #corresponds magically to show.html.erb??
    @food = Food.all #this is what it selects from the database so the html will show 
    @foodCount = Food.count
    
   @response = HTTParty.get("http://api.nal.usda.gov/ndb/reports/?ndbno=01009&type=f&format=json&api_key=DEMO_KEY").parsed_response
    
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def homepage
    

  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
   def userCount
       @userCount = User.count
   end
    
    def fullsticky_title(sticky_title = '')
        base_sticky = ""
        if sticky_title.empty?
            base_sticky
        else
            sticky_title
        end
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/exercises/categories.html.erb
<%= content_for :title, "Calories to Miles | Categories" %>
<%= content_for :sticky_title, "Categories" %>


<div class="table-responsive">
<table = id="exercise-category-table" class="table table-condensed table-striped">
<tr>
    <th>Category</th>
    <th>Number of Exercises</th>
</tr>
<tr>
    
</tr>
<tr>
<% @descriptionCount.each do |k,v| %>
</tr>
<td>
<%= k %>

</td>
<td>
<%= v %>
</td>
</tr>

<% end %>

</table>
</div>

app/views/exercises/database.html.erb
<%= content_for :title, "Calories to Miles | Exercise Database" %>
<%= content_for :sticky_title, "Exercise Database" %>


<p class="lead">There are currently <%= pluralize @exerciseCount, 'record', 'records' %> in the database representing <%= link_to pluralize(@categoryCount, 'category', 'categories'), exercise_categories_path %>.



<%= will_paginate  %>

<div class="table-responsive">
<table id="exercise-table" class="table table-condensed table-striped">
    <tr>
        <th>Exercise</th>
        <th>Description</th>
        <th>MET Value</th>
    </tr>
    <tr> 
        <% @exercises.each do |e| %>
    <td>
        <%= e.category %>
    </td>
    <td>
        <%= e.description %>
    </td>
    <td>
        <%= e.met %>
    </td>
</tr>
<% end %>
</table>
</div>

<%= will_paginate  %>

app/views/exercises/results.html.erb
<!-- This page will show the results of the calculation made from show.html.erb. -->
<%= content_for :title, "Calories to Miles | Results" %>
<%= content_for :sticky_title, "Results" %>

<div align="center"><p class="lead">It would take about <%= pluralize @minutes, 'minute', 'minutes' %> of <%= @exerciseResult.description %> 
to burn off the calories from <%= @foodResult.name %>.</p> </div>

app/views/exercises/show.html.erb
<%= content_for :title, "Calories.to | Home" %>
<%= content_for :sticky_title, "Calories.to" %>

<%= bootstrap_form_for :results, url:results_path, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do |f| %>
           
            <%= f.number_field :weight, hide_label: true, prepend: "Weight", placeholder: "(lbs)"%> 
            <% @wat = @exerciseOptions.map{ |w, x| w.size > 35 ? [w[0,35] + "...", x] : [w, x] } %>
            <%= f.select(:exercise, options_for_select(@wat), {include_blank: true, hide_label: true}) %> 
            <%= f.select(:food, options_for_select(@foodOptions), hide_label: true) %>
            <div class="text-right col-sm-10">
            <%= f.submit "Calculate", class: "btn btn-primary" %> 
            </div>
        <% end %>
</div>
    
    
  

app/views/foods/new.html.erb
<h1>Foods#new</h1>
<p>Find me in app/views/foods/new.html.erb</p>

app/views/foods/show.html.erb
<!-- This is the table to display food and calories from the database -->
<%= content_for :title, "Calories to Miles | Food Database" %>
<%= content_for :sticky_title, "Food Database" %> 

<p class="lead"> There are presently <%= @foodCount %> food <%= 'item'.pluralize(@foodCount) %> in the database.<p>

<div class="table-responsive">
<table id="food-table" class="table table-condensed table-striped">
    <tr>
        <th>Food</th>
        <th>Calories</th>
    </tr>
    <tr> 
        <% @food.limit(5).each do |food| %>
    <td>
        <%= food.name %>
    </td>
    <td>
        <%= food.calories %>
    </td>
</tr>
<% end %>
</table>
</div>
<%= @response["report"]["food"] %>  

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
  
    <span class="text-muted credit">&copy; 2015 Calories to Miles |  <%= pluralize(userCount, 'user', 'users') %> 
    <span class="glyphicon glyphicon-github" aria-hidden="true"></span>
  </div>
</div>
</div>

app/views/layouts/_header.html.erb
<div id="wrap">
  
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Calories.to ', root_path, :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%=  link_to 'Exercise Database', exercise_database_path %> </li>
          <li><%=  link_to 'Food Database', food_path %></li>
          <li><%= link_to 'Credits', credits_path %></li>
          <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <li><%= link_to 'Edit profile', edit_user_registration_path %></li> 
  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to "Sign up", new_user_registration_path  %></li>
  <li><%= link_to "Login", new_user_session_path%></li>
<% end %> </p>
          
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!-- This is main application HTML -->
<!DOCTYPE html>
<html>
    <head>
      <title><%= yield(:title) %></title>
      <%= render partial: "partials/google_analytics" %>
        <meta name="viewport" content="width=device-width, initial-scale=1">`
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
  <body>
  
<!-- Show header -->

  <%= render 'layouts/header' %>

<!-- Links to pages on the application defined in config/routes.rb and directed to app/views/static_pages -->

<!-- Begin page content -->

  <div class="container">
    <div class="page-header">
      <h1><%= yield(:sticky_title) %></h1>
    </div>
    
<!-- Alert notices for login / logout -->

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<!-- By default, show the calculator form otherwise show the corresponding view user clicks on (such as about, database, etc) -->

    <%= yield %>
    
  </div>
</div>

<!-- Show the footer -->
  <%= render 'layouts/footer' %>

<!-- Google Analytics Partial -->
  <%= render partial: "partials/google_analytics_pageview" %>

  </body>
</html>

app/views/partials/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-96729-9', 'auto');
  ga('send', 'pageview');

</script>

app/views/partials/_google_analytics_pageview.html.erb
<script>
    ga('send', 'pageview', '<%= request.path %>');
</script>

app/views/static_pages/about.html.erb
<!-- This is a general about page which will display all project details -->

<%= content_for :title, "Calories to Miles | About" %>
<%= content_for :sticky_title, "About" %>
<!-- Put an H1 title code here to show dynamically on the static h1 title -->

<p class="lead">
Data has been provided from the <a href="https://sites.google.com/site/compendiumofphysicalactivities/">Compendium of Physical Activities</a> and the <a href="http://ndb.nal.usda.gov/ndb/foods">USDA Food Database</a>.
The function of this application aims to provide a fun and easy way to determine exercise needs for a specified food item and quantity.</p>

app/views/static_pages/credits.html.erb
<%= content_for :title, "Calories to Miles | Credits" %>
<%= content_for :sticky_title, "Credits" %>

<p class="text-muted credit">Example courtesy <a href="http://martinbean.co.uk">Martin Bean</a> and <a href="http://ryanfait.com/sticky-footer/">Ryan Fait</a>.

app/views/static_pages/homepage.html.erb
<%= content_for :title, "Calories to Miles | Homepage" %>

app/views/static_pages/settings.html.erb
<!-- This is the settings page, eventually allowing a user to change things such as their weight, preferred activity, etc. -->

<%= content_for :title, "Calories to Miles | Settings" %>
<h1>Settings</h1>